#!/usr/bin/env python3
"""Embed an Ember .ebl image as a C array so the STM32 can XMODEM it into the EM250."""
import sys

src, dst, name = sys.argv[1], sys.argv[2], sys.argv[3]
d = open(src, "rb").read()
with open(dst, "w") as f:
    f.write(f"/* Generated by tools/ebl_to_c.py from {src.split('/')[-1]}. Do not edit. */\n")
    f.write("#include <stddef.h>\n#include <stdint.h>\n\n")
    f.write(f"const uint8_t {name}[] = {{\n")
    for i in range(0, len(d), 16):
        f.write("\t" + ",".join(f"0x{b:02x}" for b in d[i:i + 16]) + ",\n")
    f.write("};\n")
    f.write(f"const size_t {name}_len = {len(d)};\n")
print(f"{len(d)} bytes -> {dst}")
